name: My Common Action

runs:
  using: composite

  steps:
    - name: Step 1
      shell: bash
      run: echo "Hello from Step 1"

    - name: Step 2
      shell: bash
      run: echo "Hello from Step 2"

    - name: Test
      shell: bash
      run: echo built glfw on ${{ matrix.cfg.os }} in ${{ matrix.cfg.architecture }} for ${{ matrix.cfg.compiler }}

      #   - name: Build glfw
      #     working-directory: packages/glfw
      #     run: docker-compose up --build
  
      #   - name: Upload files to a GitHub release
      #     uses: svenstaro/upload-release-action@2.6.1