name: Build Package

runs:
  using: composite

  steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Invoke Python build script
      shell: bash
      run: |
        FULL_PACKAGE_NAME=${{matrix.cfg.FULL_PACKAGE_NAME}} \
        CC_COMPILER=${{matrix.cfg.CC_COMPILER}} \
        CC_COMPILER_PACKAGE=${{matrix.cfg.CC_COMPILER_PACKAGE}} \
        CXX_COMPILER=${{matrix.cfg.CXX_COMPILER}} \
        CXX_COMPILER_PACKAGE=${{matrix.cfg.CXX_COMPILER_PACKAGE}} \
        python3 -m packages.$PACKAGE.build
  
      #   - name: Upload files to a GitHub release
      #     uses: svenstaro/upload-release-action@2.6.1