name: Build Package

runs:
  using: composite

  steps:
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Invoke Python build script
      shell: bash
      run: python3 $BUILD_SCRIPT #${{ matrix.cfg.os }} in ${{ matrix.cfg.architecture }} for ${{ matrix.cfg.compiler }}
  
      #   - name: Upload files to a GitHub release
      #     uses: svenstaro/upload-release-action@2.6.1