name: My Common Action

runs:
  using: composite

  steps:
    - name: Step 1
      shell: bash
      run: echo "Hello from Step 1"

    - name: Step 2
      shell: bash
      run: echo "Hello from Step 2"