version: '3.4'

x-package: &default
  volumes:
    - .:/package
    - ../..:/repo

x-build: &build
  context: .

services:
        
  # glfw-linux-x64-gcc8:
  #   <<: *default
  #   build:
  #     <<: *build
  #     dockerfile: ../../docker/generic/Dockerfile
  #     args:
  #       - GIT_REPOSITORY=https://github.com/glfw/glfw.git
  #       - GIT_TAG=3.3.8
  #       - PACKAGE_NAME=glfw
  #       - FULL_PACKAGE_NAME=glfw-linux-x64-gcc7
  #       - CC_COMPILER_PACKAGE=gcc-8
  #       - CC_COMPILER=gcc-8
  #       - CXX_COMPILER_PACKAGE=g++-8
  #       - CXX_COMPILER=g++-8

  # glfw-linux-x64-clang7:
  #   <<: *default
  #   build:
  #     <<: *build
  #     dockerfile: ../../docker/generic/Dockerfile
  #     args:
  #       - GIT_REPOSITORY=https://github.com/glfw/glfw.git
  #       - GIT_TAG=3.3.8
  #       - PACKAGE_NAME=glfw
  #       - FULL_PACKAGE_NAME=glfw-linux-x64-clang7
  #       - CC_COMPILER_PACKAGE=clang-7
  #       - CC_COMPILER=clang-7
  #       - CXX_COMPILER_PACKAGE=clang++-7
  #       - CXX_COMPILER=clang++-7
  
  # glfw-linux-x64-mingw: 
  #   <<: *default
  #   build:
  #     <<: *build
  #     dockerfile: ../../docker/generic/Dockerfile
  #     args:
  #       - GIT_REPOSITORY=https://github.com/glfw/glfw.git
  #       - GIT_TAG=3.3.8
  #       - PACKAGE_NAME=glfw
  #       - FULL_PACKAGE_NAME=glfw-linux-x64-mingw
  #       - CC_COMPILER_PACKAGE=gcc-mingw-w64
  #       - CC_COMPILER=x86_64-w64-mingw32-gcc
  #       - CXX_COMPILER_PACKAGE=g++-mingw-w64
  #       - CXX_COMPILER=x86_64-w64-mingw32-g++
  #       - TOOLCHAIN_FILE=/repo/toolchains/mingw.cmake # MinGW toolchain file
        
  glfw-linux-arm64-gcc8:
    <<: *default
    build:
      <<: *build
      dockerfile: ../../docker/generic/Dockerfile
      args:
        - GIT_REPOSITORY=https://github.com/glfw/glfw.git
        - GIT_TAG=3.3.8
        - PACKAGE_NAME=glfw
        - FULL_PACKAGE_NAME=glfw-linux-arm64-gcc8
        - CC_COMPILER_PACKAGE=gcc-8-aarch64-linux-gnu
        - CC_COMPILER=aarch64-linux-gnu-gcc-8
        - CXX_COMPILER_PACKAGE=g++-8-aarch64-linux-gnu
        - CXX_COMPILER=aarch64-linux-gnu-g++-8
        
  # glfw-windows-amd64-msvc:
  #   <<: *default
  #   build:
  #     <<: *build
  #     dockerfile: ../../docker/msvc/Dockerfile
  #     args:
  #       - GIT_REPOSITORY=https://github.com/glfw/glfw.git
  #       - GIT_TAG=3.3.8
  #       - PACKAGE_NAME=glfw
  #       - FULL_PACKAGE_NAME=glfw-windows-amd64-msvc
  #       - CC_COMPILER_PACKAGE=msvc
  #       - CC_COMPILER=msvc
  #       - CXX_COMPILER_PACKAGE=msvc
  #       - CXX_COMPILER=msvc