name: Build glfw

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        manual:

          - os: windows
            architecture: [ x64 ]
            compiler: [ msvc, mingw, msys2, clang ]

          - os: linux
            architecture: [ x64, arm64 ]
            compiler: [ gcc, clang, mingw ]

          - os: android
            architecture: [ arm64 ]
            compiler: [ gcc, clang ]

          - os: emscripten
            architecture: [ emscripten ]
            compiler: [ emscripten ]

          - os: macos
            architecture: [ x64, arm64 ]
            compiler: [ gcc, clang ]

          - os: tvos
            architecture: [ x64, arm64 ]
            compiler: [ gcc, clang ]

          - os: ios
            architecture: [ arm64 ]
            compiler: [ gcc, clang ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Common Action
        uses: ./.github/actions/build-package

