name: Build glfw

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        architecture: [x86_64, arm64]
        manual:
          - package: 'glfw'
          - package: 'libpng'
          - package: 'zlib'
          - package: 'tess2'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: echo built ${{ matrix.manual.package }} for ${{ matrix.architecture }} && pwd && ls .github && pwd .github/actions/build-package.yaml

      - name: Use Common Action
        uses: ./.github/actions/build-package.yaml

    #   - name: Build glfw
    #     working-directory: packages/glfw
    #     run: docker-compose up --build

    #   - name: Upload files to a GitHub release
    #     uses: svenstaro/upload-release-action@2.6.1

