name: Build glfw

on:
  push:
    paths:
      - 'packages/glfw/**'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build glfw
        working-directory: packages/glfw
        run: docker-compose up --build
