# name: Test

# on:
#   push:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: windows-2019

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Test
#         run: cd packages/glfw/test && docker-compose up --build

